package com.rip.sql.service;

import com.rip.sql.ddl.DDL_Genarator;
import com.rip.sql.util.JavaMainFileRunner;
import com.rip.sql.util.WriteToJSONFile;
import org.json.JSONObject;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

@Service("DDLManagementService")
public class DDLManagementServiceImpl implements DDLManagementService {

    @Autowired
    DDL_Genarator dDL_Genarator;
    
    @Autowired
    WriteToJSONFile writeToJSONFile;
    
    @Autowired
    JavaMainFileRunner javaMainFileRunner;

    @Override
    public String genarate(String ddlJSON) {
        String dsm = "{\n"
                + "  \"rip_sql_dsm_details\": {\n"
                + "    \"rip_sql_dsm_name\": \"MySql\",\n"
                + "    \"rip_sql_dsm_version\": 5.6\n"
                + "  },\n"
                + "  \"rip_sql_dsm_data_types\": {\n"
                + "    \"rip_sql_short_string\": \"VARCHAR(10)\",\n"
                + "    \"rip_sql_mediam_string\": \"VARCHAR(45)\",\n"
                + "    \"rip_sql_long_string\": \"VARCHAR(1500)\",\n"
                + "    \"rip_sql_small_lnteger\": \"SMALLINT\",\n"
                + "    \"rip_sql_mediam_integer\": \"MEDIUMINT\",\n"
                + "    \"rip_sql_big_integer\": \"BIGINT\",\n"
                + "    \"rip_sql_float\": \"FLOAT(7,4)\",\n"
                + "    \"rip_sql_date_with_tz\": \"DATETIME\",\n"
                + "    \"rip_sql_date_without_tz\": \"DATETIME\",\n"
                + "    \"rip_sql_date\": \"DATETIME\",\n"
                + "    \"rip_sql_time\": \"DATETIME\",\n"
                + "    \"rip_sql_timestamp\": \"TIMESTAMP\",\n"
                + "    \"rip_sql_small_blob\": \"BLOB\",\n"
                + "    \"rip_sql_mediam_blob\": \"MEDIUMBLOB\",\n"
                + "    \"rip_sql_large_blob\": \"LONGBLOB\",\n"
                + "    \"rip_sql_xml\": \"LONGTEXT\",\n"
                + "    \"rip_sql_boolean\": \"TINYINT\"\n"
                + "  },\n"
                + "  \"rip_sql_dsm_query_create_database\": \"CREATE DATABASE rip_sql_database_name\",\n"
                + "  \"rip_sql_dsm_query_use_database\": \"USE rip_sql_database_name\",\n"
                + "  \"rip_sql_dsm_table\": \"CREATE TABLE rip_sql_table_name (\\nrip_sql_repeat_begin{\\nrip_sql_feild_name rip_sql_data_type rip_sql_not_null  rip_sql_auto_incriment\\nRip_sql_repeat_except_last_begin{ , }rip_sql_repeat_except_last_end\\n}rip_sql_repeat_end\\n\\nPRIMARY KEY (\\nrip_sql_repeat_begin{\\nRip_sql_feild_name\\nrip_sql_repeat_except_last_begin{ , }rip_sql_repeat_except_last_end\\n}rip_sql_repeat_end\\n),\\nrip_sql_repeat_begin{\\nUNIQUE INDEX rip_sql_feild_name_UNIQUE ( rip_sql_feild_name  ASC)\\nrip_sql_repeat_except_last_begin{ , }rip_sql_repeat_except_last_end\\n\\n}rip_sql_repeat_end\\n);\",\n"
                + "  \"rip_sql_dsm_fkey\": \"ALTER TABLE rip_sql_base_table\\nADD CONSTRAINT rip_sql_fk_name\\n  FOREIGN KEY ( rip_sql_bt_feild_name )\\n  REFERENCES rip_sql_reference_table ( rip_sql_rt_feild_name )\\n  ON DELETE rip_sql_on_delete\\n  ON UPDATE rip_sql_on_update;\"\n"
                + "}";

        String pim = "{\n"
                + "  \"Request_details\": {\n"
                + "    \"project_name\": \"testapp\",\n"
                + "    \"userName\": \"ghasithalakmal@gmail.com\",\n"
                + "    \"version\": \"2.0.5\",\n"
                + "    \"date_time\": \"2015-05-05 22:21:02\"\n"
                + "  },\n"
                + "  \"Technical_Spec\": {\n"
                + "    \"app_id\": 125,\n"
                + "    \"app_name\": \"testapp\",\n"
                + "    \"lanauge\": \"java\",\n"
                + "    \"build_tool\": \"maven\",\n"
                + "    \"rest_framework\": \"play\",\n"
                + "    \"orm_framework\": \"hibanate\",\n"
                + "    \"dbms\": \"mysql\",\n"
                + "    \"test_framework\": \"junit\",\n"
                + "    \"css_framework\": \"bootstrap\",\n"
                + "    \"js_framework\": \"anguler\",\n"
                + "    \"UI_theam\": \"theam1\",\n"
                + "    \"architecture\": \"template3\",\n"
                + "    \"server\": \"apache\",\n"
                + "    \"api_doccumentation_type\": \"type1\",\n"
                + "    \"technical_doccumentation_type\": \"type3\",\n"
                + "    \"test_report_type\": \"type2\",\n"
                + "    \"authontication_type\": \"Oauth2\",\n"
                + "    \"is_need_CRUD_operations_for_all\": true,\n"
                + "    \"is_need_CRUD_forms_for_all\": true\n"
                + "  },\n"
                + "  \"Database_Design\": {\n"
                + "    \"rip_sql_database_name\": \"testdb\",\n"
                + "    \"rip_sql_tables\": [\n"
                + "      {\n"
                + "        \"rip_sql_table_name\": \"employee\",\n"
                + "        \"rip_sql_fileds\": [\n"
                + "          {\n"
                + "            \"rip_sql_feild_name\": \"emp_id\",\n"
                + "            \"rip_sql_data_type\": \"rip_sql_mediam_integer\",\n"
                + "            \"rip_sql_primary_key\": true,\n"
                + "            \"rip_sql_auto_incriment\": true,\n"
                + "            \"rip_sql_not_null\": true,\n"
                + "            \"rip_sql_unique\": true\n"
                + "          },\n"
                + "          {\n"
                + "            \"rip_sql_feild_name\": \"emp_name\",\n"
                + "            \"rip_sql_data_type\": \"rip_sql_mediam_string\",\n"
                + "            \"rip_sql_primary_key\": false,\n"
                + "            \"rip_sql_auto_incriment\": false,\n"
                + "            \"rip_sql_not_null\": true,\n"
                + "            \"rip_sql_unique\": false\n"
                + "          },\n"
                + "          {\n"
                + "            \"rip_sql_feild_name\": \"emp_phone\",\n"
                + "            \"rip_sql_data_type\": \"rip_sql_mediam_integer\",\n"
                + "            \"rip_sql_primary_key\": false,\n"
                + "            \"rip_sql_auto_incriment\": false,\n"
                + "            \"rip_sql_not_null\": false,\n"
                + "            \"rip_sql_unique\": true\n"
                + "          },\n"
                + "          {\n"
                + "            \"rip_sql_feild_name\": \"emp_address\",\n"
                + "            \"rip_sql_data_type\": \"rip_sql_mediam_string\",\n"
                + "            \"rip_sql_primary_key\": false,\n"
                + "            \"rip_sql_auto_incriment\": false,\n"
                + "            \"rip_sql_not_null\": false,\n"
                + "            \"rip_sql_unique\": false\n"
                + "          },\n"
                + "          {\n"
                + "            \"rip_sql_feild_name\": \"emp_dep_id\",\n"
                + "            \"rip_sql_data_type\": \"rip_sql_mediam_integer\",\n"
                + "            \"rip_sql_primary_key\": false,\n"
                + "            \"rip_sql_auto_incriment\": false,\n"
                + "            \"rip_sql_not_null\": true,\n"
                + "            \"rip_sql_unique\": true\n"
                + "          }\n"
                + "        ]\n"
                + "      },\n"
                + "      {\n"
                + "        \"rip_sql_table_name\": \"vision\",\n"
                + "        \"rip_sql_fileds\": [\n"
                + "          {\n"
                + "            \"rip_sql_feild_name\": \"vision_id\",\n"
                + "            \"rip_sql_data_type\": \"rip_sql_mediam_integer\",\n"
                + "            \"rip_sql_primary_key\": true,\n"
                + "            \"rip_sql_auto_incriment\": true,\n"
                + "            \"rip_sql_not_null\": true,\n"
                + "            \"rip_sql_unique\": true\n"
                + "          },\n"
                + "          {\n"
                + "            \"rip_sql_feild_name\": \"vision_name\",\n"
                + "            \"rip_sql_data_type\": \"rip_sql_mediam_string\",\n"
                + "            \"rip_sql_primary_key\": false,\n"
                + "            \"rip_sql_auto_incriment\": false,\n"
                + "            \"rip_sql_not_null\": true,\n"
                + "            \"rip_sql_unique\": false\n"
                + "          },\n"
                + "          {\n"
                + "            \"rip_sql_feild_name\": \"vision_des\",\n"
                + "            \"rip_sql_data_type\": \"rip_sql_mediam_string\",\n"
                + "            \"rip_sql_primary_key\": false,\n"
                + "            \"rip_sql_auto_incriment\": false,\n"
                + "            \"rip_sql_not_null\": true,\n"
                + "            \"rip_sql_unique\": false\n"
                + "          }\n"
                + "        ]\n"
                + "      },\n"
                + "      {\n"
                + "        \"rip_sql_table_name\": \"department\",\n"
                + "        \"rip_sql_fileds\": [\n"
                + "          {\n"
                + "            \"rip_sql_feild_name\": \"dep_id\",\n"
                + "            \"rip_sql_data_type\": \"rip_sql_mediam_integer\",\n"
                + "            \"rip_sql_primary_key\": true,\n"
                + "            \"rip_sql_auto_incriment\": true,\n"
                + "            \"rip_sql_not_null\": true,\n"
                + "            \"rip_sql_unique\": true\n"
                + "          },\n"
                + "          {\n"
                + "            \"rip_sql_feild_name\": \"dep_name\",\n"
                + "            \"rip_sql_data_type\": \"rip_sql_mediam_string\",\n"
                + "            \"rip_sql_primary_key\": false,\n"
                + "            \"rip_sql_auto_incriment\": false,\n"
                + "            \"rip_sql_not_null\": true,\n"
                + "            \"rip_sql_unique\": false\n"
                + "          },\n"
                + "          {\n"
                + "            \"rip_sql_feild_name\": \"dep_des\",\n"
                + "            \"rip_sql_data_type\": \"rip_sql_mediam_string\",\n"
                + "            \"rip_sql_primary_key\": false,\n"
                + "            \"rip_sql_auto_incriment\": false,\n"
                + "            \"rip_sql_not_null\": true,\n"
                + "            \"rip_sql_unique\": false\n"
                + "          },\n"
                + "          {\n"
                + "            \"rip_sql_feild_name\": \"dep_vis\",\n"
                + "            \"rip_sql_data_type\": \"rip_sql_mediam_string\",\n"
                + "            \"rip_sql_primary_key\": false,\n"
                + "            \"rip_sql_auto_incriment\": false,\n"
                + "            \"rip_sql_not_null\": true,\n"
                + "            \"rip_sql_unique\": false\n"
                + "          }\n"
                + "        ]\n"
                + "      },\n"
                + "      {\n"
                + "        \"rip_sql_table_name\": \"project\",\n"
                + "        \"rip_sql_fileds\": [\n"
                + "          {\n"
                + "            \"rip_sql_feild_name\": \"pro_id\",\n"
                + "            \"rip_sql_data_type\": \"rip_sql_mediam_integer\",\n"
                + "            \"rip_sql_primary_key\": true,\n"
                + "            \"rip_sql_auto_incriment\": true,\n"
                + "            \"rip_sql_not_null\": true,\n"
                + "            \"rip_sql_unique\": true\n"
                + "          },\n"
                + "          {\n"
                + "            \"rip_sql_feild_name\": \"pro_name\",\n"
                + "            \"rip_sql_data_type\": \"rip_sql_mediam_string\",\n"
                + "            \"rip_sql_primary_key\": false,\n"
                + "            \"rip_sql_auto_incriment\": false,\n"
                + "            \"rip_sql_not_null\": true,\n"
                + "            \"rip_sql_unique\": false\n"
                + "          },\n"
                + "          {\n"
                + "            \"rip_sql_feild_name\": \"pro_des\",\n"
                + "            \"rip_sql_data_type\": \"rip_sql_mediam_string\",\n"
                + "            \"rip_sql_primary_key\": false,\n"
                + "            \"rip_sql_auto_incriment\": false,\n"
                + "            \"rip_sql_not_null\": true,\n"
                + "            \"rip_sql_unique\": false\n"
                + "          }\n"
                + "        ]\n"
                + "      },\n"
                + "      {\n"
                + "        \"rip_sql_table_name\": \"employee_workson_project\",\n"
                + "        \"rip_sql_fileds\": [\n"
                + "          {\n"
                + "            \"rip_sql_feild_name\": \"emp_id_ref\",\n"
                + "            \"rip_sql_data_type\": \"rip_sql_mediam_integer\",\n"
                + "            \"rip_sql_primary_key\": true,\n"
                + "            \"rip_sql_auto_incriment\": false,\n"
                + "            \"rip_sql_not_null\": true,\n"
                + "            \"rip_sql_unique\": true\n"
                + "          },\n"
                + "          {\n"
                + "            \"rip_sql_feild_name\": \"pro_id_ref\",\n"
                + "            \"rip_sql_data_type\": \"rip_sql_mediam_integer\",\n"
                + "            \"rip_sql_primary_key\": true,\n"
                + "            \"rip_sql_auto_incriment\": false,\n"
                + "            \"rip_sql_not_null\": true,\n"
                + "            \"rip_sql_unique\": true\n"
                + "          }\n"
                + "        ]\n"
                + "      }\n"
                + "    ],\n"
                + "    \"forign_keys\": [\n"
                + "      {\n"
                + "        \"rip_sql_fk_name\": \"emp_fk\",\n"
                + "        \"rip_sql_base_table\": \"employee_workson_project\",\n"
                + "        \"rip_sql_bt_feild_name\": \"emp_id_ref\",\n"
                + "        \"rip_sql_reference_table\": \"employee\",\n"
                + "        \"rip_sql_rt_feild_name\": \"emp_id\",\n"
                + "        \"rip_sql_on_delete\": \"CASCADE\",\n"
                + "        \"rip_sql_on_update\": \"CASCADE\"\n"
                + "      },\n"
                + "      {\n"
                + "        \"rip_sql_fk_name\": \"pro_fk\",\n"
                + "        \"rip_sql_base_table\": \"employee_workson_project\",\n"
                + "        \"rip_sql_bt_feild_name\": \"pro_id_ref\",\n"
                + "        \"rip_sql_reference_table\": \"project\",\n"
                + "        \"rip_sql_rt_feild_name\": \"pro_id\",\n"
                + "        \"rip_sql_on_delete\": \"CASCADE\",\n"
                + "        \"rip_sql_on_update\": \"CASCADE\"\n"
                + "      },\n"
                + "      {\n"
                + "        \"rip_sql_fk_name\": \"dep_fk\",\n"
                + "        \"rip_sql_base_table\": \"employee\",\n"
                + "        \"rip_sql_bt_feild_name\": \"emp_dep_id\",\n"
                + "        \"rip_sql_reference_table\": \"department\",\n"
                + "        \"rip_sql_rt_feild_name\": \"dep_id\",\n"
                + "        \"rip_sql_on_delete\": \"CASCADE\",\n"
                + "        \"rip_sql_on_update\": \"CASCADE\"\n"
                + "      },\n"
                + "      {\n"
                + "        \"rip_sql_fk_name\": \"vision_fk\",\n"
                + "        \"rip_sql_base_table\": \"department\",\n"
                + "        \"rip_sql_bt_feild_name\": \"dep_vis\",\n"
                + "        \"rip_sql_reference_table\": \"vision\",\n"
                + "        \"rip_sql_rt_feild_name\": \"vision_id\",\n"
                + "        \"rip_sql_on_delete\": \"CASCADE\",\n"
                + "        \"rip_sql_on_update\": \"CASCADE\"\n"
                + "      }\n"
                + "    ]\n"
                + "  },\n"
                + "  \"QueryDesign\": {\n"
                + "    \"select_queries\": [\n"
                + "      {\n"
                + "        \"queary_id\": \"s1\",\n"
                + "        \"query\": \"select * from student where stuname = ? and age > ?\",\n"
                + "        \"parameterTypes\": [\n"
                + "          \"varchar(45)\",\n"
                + "          \"int(11)\"\n"
                + "        ],\n"
                + "        \"parameterNames\": [\n"
                + "          \"stu_name\",\n"
                + "          \"stu_age\"\n"
                + "        ]\n"
                + "      },\n"
                + "      {\n"
                + "        \"queary_id\": \"s2\",\n"
                + "        \"query\": \"select * from student\"\n"
                + "      },\n"
                + "      {\n"
                + "        \"queary_id\": \"s3\",\n"
                + "        \"query\": \"select * from student\"\n"
                + "      },\n"
                + "      {\n"
                + "        \"queary_id\": \"s4\",\n"
                + "        \"query\": \"select * from student\"\n"
                + "      },\n"
                + "      {\n"
                + "        \"queary_id\": \"s5\",\n"
                + "        \"query\": [\n"
                + "          {\n"
                + "            \"table_name\": \"student\",\n"
                + "            \"table_alise\": \"stu\",\n"
                + "            \"feilds\": [\n"
                + "              {\n"
                + "                \"feild_name\": \"stuid\",\n"
                + "                \"output_name\": \"student_id\"\n"
                + "              },\n"
                + "              {\n"
                + "                \"feild_name\": \"stuname\",\n"
                + "                \"output_name\": \"student_name\"\n"
                + "              }\n"
                + "            ]\n"
                + "          },\n"
                + "          {\n"
                + "            \"table_name\": \"schools\",\n"
                + "            \"table_alise\": \"sch\",\n"
                + "            \"feilds\": [\n"
                + "              {\n"
                + "                \"feild_name\": \"schid\",\n"
                + "                \"output_name\": \"school_id\"\n"
                + "              },\n"
                + "              {\n"
                + "                \"feild_name\": \"schname\",\n"
                + "                \"output_name\": \"school_name\"\n"
                + "              }\n"
                + "            ]\n"
                + "          }\n"
                + "        ],\n"
                + "        \"where_clause\": [\n"
                + "          {}\n"
                + "        ]\n"
                + "      }\n"
                + "    ],\n"
                + "    \"insert_queries\": [\n"
                + "      {\n"
                + "        \"queary_id\": \"i1\",\n"
                + "        \"query\": \"insert into student values('a','a','a');\"\n"
                + "      },\n"
                + "      {\n"
                + "        \"queary_id\": \"i2\",\n"
                + "        \"query\": \"insert into student values('a','a','a');\"\n"
                + "      },\n"
                + "      {\n"
                + "        \"queary_id\": \"i3\",\n"
                + "        \"query\": \"insert into student values('a','a','a');\"\n"
                + "      },\n"
                + "      {\n"
                + "        \"queary_id\": \"i4\",\n"
                + "        \"query\": \"insert into student values('a','a','a');\"\n"
                + "      }\n"
                + "    ],\n"
                + "    \"update_queries\": [\n"
                + "      {\n"
                + "        \"queary_id\": \"u1\",\n"
                + "        \"query\": \"update student set age = 25 where stuid = 1;\"\n"
                + "      },\n"
                + "      {\n"
                + "        \"queary_id\": \"u2\",\n"
                + "        \"query\": \"update student set age = 25 where stuid = 1;\"\n"
                + "      },\n"
                + "      {\n"
                + "        \"queary_id\": \"u3\",\n"
                + "        \"query\": \"update student set age = 25 where stuid = 1;\"\n"
                + "      }\n"
                + "    ],\n"
                + "    \"delete_queries\": [\n"
                + "      {\n"
                + "        \"queary_id\": \"d1\",\n"
                + "        \"query\": \"delete from student where stuid = 5;\"\n"
                + "      }\n"
                + "    ]\n"
                + "  },\n"
                + "  \"RestAPI_Design\": {\n"
                + "    \"rootURI\": \"{app_name}/myapi\"\n"
                + "  },\n"
                + "  \"UI_Design\": {},\n"
                + "  \"Reload_details\": {}\n"
                + "}";
        JSONObject platformIndependentModel = new JSONObject(pim);
        
        writeToJSONFile.createJsonFile("pim", platformIndependentModel.toString());
        javaMainFileRunner.TestCode();
//        String script = javaMainFileRunner.runClass("MySQLScriptGen");
//        System.out.println(script);
        return "msg";
    }

}
